[phases.setup]
nixPkgs = ["nodejs", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm --filter \"./apps/server\" build"]

[start]
cmd = "pnpm --filter \"./apps/server\" start"
